// TypeInfo.pqm — ClickHouse native type catalog for the ADBC / Arrow Flight SQL path.
//
// This table is the authoritative type catalog for two consumers:
//   1. FlightSqlAdbcConfig.pqm selects {Name, SqlType, Unsigned, ColumnSize,
//      NumberPrecisionRadix, LiteralPrefix, LiteralSuffix} and hands it to the driver.
//   2. ClickHouseSqlGenerator.pqm derives SqlGetTypeInfo (SqlTypeName/Type/GetLiteral/...).
//
// ClickHouse does NOT implement CommandGetXdbcTypeInfo over Flight SQL, so the generic
// FlightSQL driver maps Arrow types -> ODBC SQL type codes itself. The Name/SqlType rows
// below therefore describe the SQL types the driver surfaces (keyed off Arrow), not raw
// ClickHouse type names. Arrow mappings verified against ClickHouse 26.5.
//
// Column reference (ODBC SQLGetTypeInfo semantics):
//   Name                  Native SQL type name used by the generator
//   SqlType               ODBC SQL type code
//   Type                  Equivalent Power Query M type
//   Unsigned              true for unsigned integer types
//   ColumnSize            max precision (numeric) / length (string)
//   GetLiteral            value -> SQL literal renderer
//   Searchable            WHERE-clause usability (3 = any comparison operator)
//   NumberPrecisionRadix  2 (bits) for approximate numerics, 10 for exact, null otherwise
//   LiteralPrefix/Suffix  quoting wrappers for literals
let
    // Explicit culture: SQL literals must not depend on the evaluation environment's locale
    // (decimal separators, digit shapes).
    GetNumberLiteral = (value as number) => Number.ToText(value, null, "en-US"),
    // DECIMAL literals: the engine's default serialization appends a trailing dot
    // ("18446744073709551615."), which ClickHouse parses as Float64 — rounding large values
    // (2^64-1 becomes 2^64) and silently mismatching exact comparisons. An explicit CAST from
    // a string keeps the full digits as a real Decimal (scale 10, matching the generator's
    // Decimal(38, 10) cast convention).
    GetDecimalLiteral = (value as number) =>
        "CAST('" & Number.ToText(value, null, "en-US") & "' AS Decimal(38, 10))",
    GetTimeLiteral = (value as time) => Time.ToText(value, [Format = "HH:mm:ss.FFFFFFF", Culture = "en-US"]),
    GetDateLiteral = (value as date) => Date.ToText(value, [Format = "yyyy-MM-dd", Culture = "en-US"]),
    GetDateTimeLiteral = (value as datetime) as text =>
        DateTime.ToText(value, [Format = "yyyy-MM-dd HH:mm:ss.FFFFFFF", Culture = "en-US"]),
    // ClickHouse string-literal escaping: backslash and apostrophe are the two meaningful
    // characters; the backslash must be replaced first.
    GetStringLiteral = (value as text) as text =>
        "'" & Text.Replace(Text.Replace(value, "\", "\\"), "'", "\'") & "'",
    TypeInfo = Table.FromRecords(
        {
            [
                Name = "BOOLEAN",
                SqlType = -7,
                Type = Logical.Type,
                Unsigned = false,
                ColumnSize = 1,
                GetLiteral = GetNumberLiteral,
                Searchable = 2,
                NumberPrecisionRadix = null,
                LiteralPrefix = null,
                LiteralSuffix = null
            ],
            [
                // ClickHouse Int8 -> Arrow int8 -> ODBC TINYINT
                Name = "TINYINT",
                SqlType = -6,
                Type = Int8.Type,
                Unsigned = false,
                ColumnSize = 3,
                GetLiteral = GetNumberLiteral,
                Searchable = 2,
                NumberPrecisionRadix = 2,
                LiteralPrefix = null,
                LiteralSuffix = null
            ],
            [
                // ClickHouse Int16 -> Arrow int16 -> ODBC SMALLINT
                Name = "SMALLINT",
                SqlType = 5,
                Type = Int16.Type,
                Unsigned = false,
                ColumnSize = 5,
                GetLiteral = GetNumberLiteral,
                Searchable = 2,
                NumberPrecisionRadix = 2,
                LiteralPrefix = null,
                LiteralSuffix = null
            ],
            [
                // ClickHouse Int32 / UInt16 -> Arrow int32/uint32 -> ODBC INTEGER
                Name = "INTEGER",
                SqlType = 4,
                Type = Int32.Type,
                Unsigned = false,
                ColumnSize = 10,
                GetLiteral = GetNumberLiteral,
                Searchable = 2,
                NumberPrecisionRadix = 2,
                LiteralPrefix = null,
                LiteralSuffix = null
            ],
            [
                // ClickHouse Int64 / UInt32/UInt64 -> Arrow int64/uint64 -> ODBC BIGINT
                Name = "BIGINT",
                SqlType = -5,
                Type = Int64.Type,
                Unsigned = false,
                ColumnSize = 19,
                GetLiteral = GetNumberLiteral,
                Searchable = 2,
                NumberPrecisionRadix = 2,
                LiteralPrefix = null,
                LiteralSuffix = null
            ],
            [
                // ClickHouse Float32 -> Arrow float -> ODBC REAL
                Name = "REAL",
                SqlType = 7,
                Type = Single.Type,
                Unsigned = false,
                ColumnSize = 24,
                GetLiteral = GetNumberLiteral,
                Searchable = 2,
                NumberPrecisionRadix = 2,
                LiteralPrefix = null,
                LiteralSuffix = null
            ],
            [
                // ClickHouse Float64 -> Arrow double -> ODBC DOUBLE
                Name = "DOUBLE",
                SqlType = 8,
                Type = Double.Type,
                Unsigned = false,
                ColumnSize = 53,
                GetLiteral = GetNumberLiteral,
                Searchable = 2,
                NumberPrecisionRadix = 2,
                LiteralPrefix = null,
                LiteralSuffix = null
            ],
            [
                // ClickHouse Decimal(P,S) -> Arrow decimal128/256 -> ODBC DECIMAL
                Name = "DECIMAL",
                SqlType = 2,
                Type = Decimal.Type,
                Unsigned = false,
                ColumnSize = 76,
                GetLiteral = GetDecimalLiteral,
                Searchable = 2,
                NumberPrecisionRadix = 10,
                LiteralPrefix = null,
                LiteralSuffix = null
            ],
            [
                // ClickHouse Date / Date32 -> Arrow date32[day] -> ODBC DATE
                Name = "DATE",
                SqlType = 91,
                Type = Date.Type,
                Unsigned = false,
                ColumnSize = 10,
                GetLiteral = GetDateLiteral,
                Searchable = 3,
                NumberPrecisionRadix = null,
                LiteralPrefix = "'",
                LiteralSuffix = "'"
            ],
            [
                Name = "TIME",
                SqlType = 92,
                Type = Time.Type,
                Unsigned = false,
                ColumnSize = 15,
                GetLiteral = GetTimeLiteral,
                Searchable = 3,
                NumberPrecisionRadix = null,
                LiteralPrefix = "'",
                LiteralSuffix = "'"
            ],
            [
                // ClickHouse DateTime64(N) -> Arrow timestamp[ns] -> ODBC TIMESTAMP.
                // NB: plain DateTime arrives as Arrow uint32 (epoch seconds); not yet coerced.
                Name = "TIMESTAMP",
                SqlType = 93,
                Type = DateTime.Type,
                Unsigned = false,
                ColumnSize = 29,
                GetLiteral = GetDateTimeLiteral,
                Searchable = 3,
                NumberPrecisionRadix = null,
                LiteralPrefix = "'",
                LiteralSuffix = "'"
            ],
            [
                // ClickHouse String / LowCardinality(String) -> Arrow string -> ODBC VARCHAR
                Name = "VARCHAR",
                SqlType = 12,
                Type = Text.Type,
                Unsigned = false,
                ColumnSize = 16384,
                GetLiteral = GetStringLiteral,
                Searchable = 3,
                NumberPrecisionRadix = null,
                LiteralPrefix = "'",
                LiteralSuffix = "'"
            ],
            [
                // ClickHouse FixedString(N) / Int128/256 / IPv6 -> Arrow fixed_size_binary -> ODBC BINARY
                Name = "BINARY",
                SqlType = -2,
                Type = Binary.Type,
                Unsigned = false,
                ColumnSize = 16384,
                GetLiteral = null,
                Searchable = 2,
                NumberPrecisionRadix = null,
                LiteralPrefix = null,
                LiteralSuffix = null
            ],
            [
                // ClickHouse Array(T) -> Arrow list. Surfaced as text to the generator for now.
                Name = "ARRAY",
                SqlType = 12,
                Type = Text.Type,
                Unsigned = false,
                ColumnSize = 16384,
                GetLiteral = null,
                Searchable = 3,
                NumberPrecisionRadix = null,
                LiteralPrefix = "'",
                LiteralSuffix = "'"
            ],
            [
                // ClickHouse Tuple / Nested / Map -> Arrow struct/map. Surfaced as text for now.
                Name = "STRUCT",
                SqlType = 12,
                Type = Text.Type,
                Unsigned = false,
                ColumnSize = 16384,
                GetLiteral = null,
                Searchable = 3,
                NumberPrecisionRadix = null,
                LiteralPrefix = "'",
                LiteralSuffix = "'"
            ]
        }
    )
in
    TypeInfo
